name: First workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello from the first job"

      - name: Print Bye
        run: echo "Good Bye"
